// Code generated by "stringer -type=Orientation -linecomment"; DO NOT EDIT.

package planar

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClockwiseOrientation - -1]
	_ = x[CoLinearOrientation-0]
	_ = x[CounterClockwiseOrientation-1]
}

const _Orientation_name = "clockwisecolinearcounter clockwise"

var _Orientation_index = [...]uint8{0, 9, 17, 34}

func (i Orientation) String() string {
	i -= -1
	if i < 0 || i >= Orientation(len(_Orientation_index)-1) {
		return "Orientation(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Orientation_name[_Orientation_index[i]:_Orientation_index[i+1]]
}
